#!/usr/bin/python3

# https://leetcode.com/problems/add-two-numbers/description/

listA = [2,3,4]
listB = [5,6,4]

def list2num(list1):
    index = 1
    final = 0
    for i in list1:
        final += int(i)*index
        index *= 10
    return(final)

print(list2num(listA) + list2num(listB))
